// Regenerates vendor/liblouis/tables.js from the table source files in
// vendor/liblouis/tables/. Run with:  node tools/gen-tables.js
//
// We inline the (small) UEB table files as base64 so the browser needs no
// network fetch — this keeps the app working when opened directly from disk
// (file://) and makes load fully synchronous.
const fs = require("fs");
const path = require("path");

const dir = path.resolve(__dirname, "../vendor/liblouis/tables");
// The include-closure of en-ueb-g1.ctb + en-ueb-g2.ctb, plus the unicode
// display table used to render dots as Unicode braille (U+2800 block).
const files = [
  "en-ueb-g1.ctb",
  "en-ueb-g2.ctb",
  "en-ueb-chardefs.uti",
  "braille-patterns.cti",
  "latinLetterDef8Dots.uti",
  "en-ueb-math.ctb",
  "unicode.dis",
];

let out = "// AUTO-GENERATED by tools/gen-tables.js — do not edit by hand.\n";
out += "// Inlines the liblouis UEB table files (base64, UTF-8 bytes) so the app needs\n";
out += "// no network fetch and works even when opened directly from disk (file://).\n";
out += "// Tables are from liblouis (LGPLv3) — see vendor/liblouis/LICENSE.\n";
out += "window.LIBLOUIS_TABLES = {\n";
for (const f of files) {
  const b64 = fs.readFileSync(path.join(dir, f)).toString("base64");
  out += "  " + JSON.stringify(f) + ": \"" + b64 + "\",\n";
}
out += "};\n";

fs.writeFileSync(path.resolve(dir, "../tables.js"), out);
console.log("wrote vendor/liblouis/tables.js (" + (out.length / 1024).toFixed(0) + " KB)");
